version: '3.7'

services:
  app:
    build: .
    container_name: availability-checker
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./products.json:/app/products.json
      - ./screenshots:/app/screenshots
    env_file: .env
