version: '3.7'

services:
  node:
    build: .
    container_name: availability-checker
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
      - ./products.json:/app/products.json
    env_file: .env

volumes:
  logs:
