services:
  app:
    build: .
    container_name: availability-checker
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
      - ./src/products.json:/app/products.json
    env_file: .env
